apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: co7w06spq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: co7w06spq-python 
  name: co7w06spq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: co7w06spq-python 
